from typing import Any
from agent_c.prompting.prompt_section import PromptSection, property_bag_item


class DynamicsCRMPrompt(PromptSection):
    def __init__(self, **data: Any):
        template = ("The Dynamics toolsets allow you to retrieve and manipulate data from Microsoft Dynamics CRM using odata query parameters. The get_entities function is optimized to return only necessary fields by default to improve efficiency and reduce token usage. You can use the 'fields' parameter to specify exactly which fields you want returned, overriding the default fields. This is useful when you only need a few specific fields and want to minimize token usage. "
                    "You can use these toolsets to search for accounts, opportunities, and leads by their partial names. "
                    "The toolsets are designed to handle authorization and provide accurate results even with partial or fuzzy matches. "
                    "When multiple accounts, leads, or opportunities are found and the user is asking for activity summaries, "
                    "the assistant will ask the user to specify which entity they would like to know more about before executing. "
                    "Be advised that when a user asks for their tasks the query_params should include the $$filter= because they query will include their _ownerid value as a filter criteria\n "
                    "<SPECIAL INSTRUCTIONS>"
                    "1) When the user is asking for filtering by specific fields that return a GUID, break up the query "
                    "into smaller queries and pass in the subsequent GUID filter criteria.\n"
                    "2) When multiple entities are saved to a file, always tell teh user about the file and where it is saved.\n"
                    "Display all the entities in the response message to the user.  Do not truncate.\n"
                    "3) When the user requests entities, especially opportunities, related to a service offering you have to filter on the 3 service offering fields such as: _cen_serviceofferingcapabiity1_value, _cen_serviceofferingcapability2_value, _cen_serviceofferingcapability3_value\n"
                    "4) When the user requests filtering based on primary service offering you have to filter on the first service offering field such as: _cen_serviceofferingcapabiity1_value\n"
                    "5) When searching for an entity by name, consider using the 'contains' function to find partial matches.\n"
                    "6) For single word account names, consider searching multiple fields, such as 'name' and 'websiteurl'.\n"
                    "7) For single word contact names, consider searching multiple fields, such as 'name' and 'email'.\n"
                    "8) Refer to your examples for the way query_params are constructed for various requests. Draw on these examples and your knowledge of Microsoft Dynamics queries for creating proper OData queries.\n"
                    "</SPECIAL INSTRUCTIONS>"
                    "<COMMON ABBREVIATIONS>"
                    "Business Unit (BU) - typically a city name like Chicago, etc... is identified by a unique identifier known as a GUID, which is typically stored in the owningbusinessunit field on records. To filter records by a specific Business Unit you will need to look up the associated GUID and filter on that\n"
                    "Service Offering (SO) - typically a team name like Modern Software Delivery, Modern Work, Salesforce, People & Change, etc... is identified by a unique identifier known as a GUID, can typically be in several fields: _cen_serviceofferingcapabiity1_value, _cen_serviceofferingcapability2_value, _cen_serviceofferingcapability3_value,   field on records. To filter records by a specific Service you will need to look up the associated GUID and typically filter with an or condition on those 3 fields\n"
                    "Industry Vertical (IV) - typically an industry like Insurance, Healthcare, Energy & Utilities, etc... is identified by a unique identifier known as a GUID, which is typically stored in the _cen_centricindustryvertical_value field on records. To filter records by a specific Industry Veritical you will need to look up the associated GUID and filter on that\n"
                    "Capability - typically a sub-category for a SO, like Agile, Custom App Dev, etc... is identified by a unique identifier known as a GUID, which is typically stored in the _cen_centricivcapability_value field on records. To filter records by a specific Capability you will need to look up the associated GUID and filter on that\n"
                    "</COMMON ABBREVIATIONS>"
                    "<COMMONLY REQUESTED FIELDS>"
                    "AI - A true/false fields usually called cen_ai, indicates if an entity record is related to AI or not. True means it is related to AI\n"
                    "Estimated Revenue - for opportunities usually the estimatedvalue field, for leads usually the budgetamount field\n"
                    "Weighted Revenue - for opportunities usually the cen_weightedrevenue field\n"
                    "Project or Staff Aug - A true/false fields usually called cen_projectflag, indicates if an entity record is related to a project or staff aug. True means a project\n"
                    "</COMMONLY REQUESTED FIELDS>"
                    "<EXAMPLES>"
                    "<ACCOUNT LOOKUP EXAMPLES>"
                    "User: 'Find an account with the name containing with Acme' or 'Get the OMIG account from Dynamics'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'account', 'query_params': \"$$select=*&$$filter=contains(name, 'Acme') or contains(websiteurl, 'Acme')\" **\n"
                    "Assistant: 'I found 2 matches for the account name 'Acme' is 'Acme Corporation' "
                    "1. Acme LLC - 555-1234 - d379023d-2549-ef11-a317-7c1e520a0a03 "
                    "2. Acme Corporation - 555-1234 - d379023d-2549-ef11-a317-7c1e520a0a04' "
                    "Which one would you like to know more about?'\n"
                    "\n"
                    "User: 'Find an account with the name containing with Acme Corporation'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'account', 'query_params': \"$$select=*&$$filter=contains(name, 'Acme Corporation')\" **\n"
                    "Assistant: 'I found 2 matches for the account name 'Acme' is 'Acme Corporation' "
                    "1. New Acme Corporation - 555-1234 - d379023d-2549-ef11-a317-7c1e520a0a03 "
                    "2. Acme Corporation - 555-1234 - d379023d-2549-ef11-a317-7c1e520a0a04' "
                    "Which one would you like to know more about?' "
                    "\n"
                    "User: 'Find an account with the id of d379023d-2549-ef11-a317-7c1e520a0a03'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'account', 'entity_id': \"d379023d-2549-ef11-a317-7c1e520a0a03\" **\n"
                    "Assistant: 'Here is the 'Acme Corporation' with ID '12345' and telephone '555-1234'.'\n"
                    "\n"
                    "User: 'Return, Get, Find all open opportunities for the OMIG account that were created this year.\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'opportunities', 'query_params': \"$$select=*&$$filter=createdon ge 2024-01-01 and"
                    " (contains(parentaccountid/name, 'OMIG') or contains(parentaccountid/websiteurl, 'omig')) "
                    "&$$expand=parentaccountid($$select=name,accountid,websiteurl)"
                    "&$$orderby=createdon desc\" **\n"
                    "Assistant: 'Here are the Opportunities for account: Ohio Mutual Insurance Group - d379023d-2549-ef11-a317-7c1e520a0a03.' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "</ACCOUNT LOOKUP EXAMPLES>"
                    "<OPPORTUNITY LOOKUP EXAMPLES>"
                    "User: 'What are the closed and won opportunities for the cybersecurity so that were closed in 2024'\n"
                    "User: 'Find all the won and closed opportunities for the Cybersecurity SO that closed in 2024'\n"
                    "User: 'Find all the won and closed opportunities for any Cybersecurity SO that closed in 2024'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'cen_serviceofferingcapabilitieses', 'query_params': \"$$select=*&$$filter=contains(cen_name, 'Cybersecurity')\" **\n"
                    "** assistant uses tool dynamics-get_entities with "
                    "{ 'entity_type': 'opportunities', "
                      "'query_params': \"$$select=*&$$filter=(_cen_serviceofferingcapabiity1_value eq '2b8628fc-5cf7-ee11-a1fd-000d3a154db5' or _cen_serviceofferingcapabiity1_value eq '3644049e-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq 'b5fc43be-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq '94ec36d8-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq 'f13b4bff-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq '6d1c30ef-8422-ee11-9cbd-00224820ea82') or "
                      " (_cen_serviceofferingcapability2_value eq '2b8628fc-5cf7-ee11-a1fd-000d3a154db5' or _cen_serviceofferingcapability2_value eq '3644049e-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability2_value eq 'b5fc43be-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability2_value eq '94ec36d8-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability2_value eq 'f13b4bff-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability2_value eq '6d1c30ef-8422-ee11-9cbd-00224820ea82') or "
                      " (_cen_serviceofferingcapability3_value eq '2b8628fc-5cf7-ee11-a1fd-000d3a154db5' or _cen_serviceofferingcapability3_value eq '3644049e-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability3_value eq 'b5fc43be-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability3_value eq '94ec36d8-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability3_value eq 'f13b4bff-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapability3_value eq '6d1c30ef-8422-ee11-9cbd-00224820ea82')) and "
                      " (statecode eq 1 and statuscode eq 3 and actualclosedate ge 2024-01-01 and actualclosedate le 2024-12-31) **\n"
                    "Assistant: 'Here are the opportunities.' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "The full list of opportunities can be found in the saved file opportunities_20240806_180209.xlsx\n"
                    "\n"
                    "User: 'Find all the closed opporturtunites in 2024 that were won where the Cybersecurity was the primary SO'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'cen_serviceofferingcapabilitieses', 'query_params': \"$$select=*&$$filter=contains(cen_name, 'Cybersecurity')\" **\n"
                    "** assistant uses tool dynamics-get_entities with "
                    "{ 'entity_type': 'opportunities', "
                      "'query_params': \"$$select=*&$$filter=(_cen_serviceofferingcapabiity1_value eq '2b8628fc-5cf7-ee11-a1fd-000d3a154db5' or _cen_serviceofferingcapabiity1_value eq '3644049e-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq 'b5fc43be-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq '94ec36d8-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq 'f13b4bff-722a-ee11-bdf4-0022481fb331' or _cen_serviceofferingcapabiity1_value eq '6d1c30ef-8422-ee11-9cbd-00224820ea82') and statecode eq 1 and statuscode eq 3 and actualclosedate ge 2024-01-01 and actualclosedate le 2024-12-31 **\n"
                    "Assistant: 'Here are the opportunities ' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "The full list of opportunities can be found in the saved file opportunities_20240806_180209.xlsx\n"
                    "</OPPORTUNITY LOOKUP EXAMPLES>"
                    "<ACTIVITY LOOKUP EXAMPLES>"
                    "User: 'Summarize all activity for the AI opportunity at Red Roof'\n"
                    "** assistant uses tool dynamics-get_entities with\n"
                    "'entity_type': 'opportunities', 'query_params': \"$$select=*&$$filter=contains(name, 'AI') and (contains(parentaccountid/name, 'Red Roof') or contains(parentaccountid/websiteurl, 'redroof'))&$$expand=parentaccountid($$select=name,accountid,websiteurl)\" **\n"
                    "Assistant: 'Here are the opportunities for the Red Roof Inn Account - 4442bf90-b6e7-ee11-904c-000d3a4f8a99.' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "Which one would you like a summary of?\n"
                    "User: 'Summarize #1' "
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'posts', 'query_params': '$$select=*&$$filter=_regardingobjectid_value eq 3462bf90-b6e7-ee11-904c-000d3a4f8a84&$$select=createdon,text&$$orderby=createdon desc&$$top=5 **\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'emails', 'query_params': '$$select=*&$$filter=_regardingobjectid_value eq 3462bf90-b6e7-ee11-904c-000d3a4f8a84&$$select=subject,description,sender,createdon&$$orderby=createdon desc&$$top=5 **\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'phonecalls', 'query_params': '$$select=*&$$filter=_regardingobjectid_value eq 3462bf90-b6e7-ee11-904c-000d3a4f8a84&$$select=subject,description,phonenumber,directioncode,createdon&$$orderby=createdon desc&$$top=5 **\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'appointments', 'query_params': '$$select=*&$$filter=_regardingobjectid_value eq 3462bf90-b6e7-ee11-904c-000d3a4f8a84&$$select=subject,description,location,scheduledstart,scheduledend,createdon&$$orderby=createdon desc&$$top=5 **\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'tasks', 'query_params': '$$select=*&$$filter=_regardingobjectid_value eq 3462bf90-b6e7-ee11-904c-000d3a4f8a84&$$select=subject,description,scheduledend,statecode,createdon&$$orderby=createdon desc&$$top=5 **\n"
                    "Assistant: Here is a summary of the activity for the 'New Business' opportunity at Red Roof Inn "
                    "A proposal has been sent to the client.  Multiple attempts to gain an update have been attempted. "
                    "I recommend attempting to call the client again to gain some feedback on the proposal sent. "
                    "Below are the most recent activities: "                    
                    "1. Summary of email from: Proposal Check Up -  4.23.2024 "
                    "2. Summary of Notes: Will reach out to contact - 4.20.2024 "
                    "3. Summary of email: Here is your proposal - 4.19.2024 "
                    "4. Call to 614.555.1212 - 4.19.2024 "
                    "5. Summary of email: Thank you for allowing us to present - 4.18.2024\n"
                    "\n"
                    "User: 'Get all open tasks assigned to me'\n"
                    "** assistant uses tool dynamics-dynamics_user_id to get the user id to use as _ownerid_value **\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'tasks', 'query_params': '$$select=*&$$filter=_ownerid_value eq 4442bf90-b6e7-ee11-904c-000d3a4f4444 and statecode eq 0&$$orderby=scheduledend asc&$$select=subject,scheduledend,statecode& **\n"
                    "Below are the open tasks:"                    
                    "1. Send note on Proposal Check Up -  4.23.2024\n"
                    "\n"
                    "User: 'Get all open tasks assigned to me for the Red Roof Account'\n"
                    "** assistant uses tool dynamics-dynamics_user_id to get the user id to use as _ownerid_value**\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'tasks', 'query_params': '$$select=*&$$filter=statecode eq 0 and _ownerid_value eq 2b3f3524-7856-e911-a82d-000d3a1a2282 and _regardingobjectid_value eq 75a522f2-a3d4-e911-a839-000d3a17ce77&$$expand=regardingobjectid_account($$select=name,accountid,websiteurl)&$$select=subject,description,scheduledend,createdon,_regardingobjectid_value&$$orderby=scheduledend asc **\n"
                    "Below are the open tasks:"                    
                    "1. Send note on Proposal Check Up -  4.23.2024\n"
                    "\n"
                    "User: 'Get all my open tasks assigned to me for the AI opportunity for Red Roof Account'\n"
                    "** assistant uses tool dynamics-dynamics_user_id to get the user id to use as _ownerid_value**\n"
                    "'entity_type': 'opportunities', 'query_params': \"$$select=*&$$filter=contains(name, 'AI') and (contains(parentaccountid/name, 'Red Roof') or contains(parentaccountid/websiteurl, 'redroof'))&$$expand=parentaccountid($$select=name,websiteurl)\" **\n"
                    "Assistant: 'Here are the opportunities for the Red Roof Inn Account - 4442bf90-b6e7-ee11-904c-000d3a4f8a99.' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "Which one would you like your tasks for?"
                    "User: '#1'\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type':'tasks', 'query_params': '$$select=*&$$filter=statecode eq 0 and _regardingobjectid_value eq 90cb1721-62ca-ee11-9079-0022481fb1b9&$$expand=regardingobjectid_opportunity($$select=name,opportunityid)&$$select=subject,description,scheduledend,createdon,statecode,statuscode&$$orderby=scheduledend asc& **\n"
                    "Below are the open tasks: "                    
                    "1. Send note on Proposal Check Up -  4.23.2024\n"
                    "</ACTIVITY LOOKUP EXAMPLES>"                
                    "<TASK CREATION EXAMPLES>"
                    "User: Create a task for the Red Roof Inn Account\n"
                    "** assistant uses tool dynamics-dynamics_user_id to get the user id to use as _ownerid_value**\n"
                    "** assistant uses tool dynamics-get_entities with 'entity_type': 'account', 'query_params': \"$$filter=contains(name, 'Red Roof') or contains(websiteurl, 'redroof')\" **\n"
                    "** assistant uses tool dynamics-create_entity with "
                    "'entity_type': 'tasks', 'entity_data': {'ownerid@odata.bind': '/systemusers(2b3f3524-7856-e911-a82d-000d3a1a2282)', "
                                                             "'description': 'Demo Task Add for Account', "
                                                            "'scheduledend': '2024-08-09T12:00:00Z', "
                                                            "'subject': 'Demo Task Add for Account', "
                                                            "'regardingobjectid_account_task@odata.bind': '/accounts(75a522f2-a3d4-e911-a839-000d3a17ce77)'} **\n"
                    "Assistant: 'I have created a task for the Red Roof Inn Account to call and schedule a meeting for 4.24.2024 at 12:00pm. You can view it at https://centricconsulting.crm.dynamics.com/main.aspx?pagetype=entitylist&etn=activitypointer&viewid=6cf285aa-eb20-4277-925a-3e9735411ff0&viewType=1039'\n"
                    "\n"
                    "User: Create a task for the AI opportunity at the Red Roof Inn Account\n"
                    "** assistant uses tool dynamics-dynamics_user_id to get the user id to use as _ownerid_value **\n"
                    "'entity_type': 'opportunities', 'query_params': \"$$select=*&$$filter=contains(name, 'AI') and (contains(parentaccountid/name, 'Red Roof') or contains(parentaccountid/websiteurl, 'redroof'))&$$expand=parentaccountid($$select=name,websiteurl)\" **\n"
                    "Assistant: 'Here are the opportunities for the Red Roof Inn Account - 4442bf90-b6e7-ee11-904c-000d3a4f8a99.' "
                    "1. Opportunity: 'New Business' - 01/07/2024 - $$250,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. Opportunity: 'Renewal' - - 04/07/2024 - $$150,000 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "Which one would you like your tasks for?"
                    "User: '#1'\n"
                    "** assistant uses tool dynamics-create_entity with "
                    "'entity_type': 'tasks', 'entity_data': {'ownerid@odata.bind': '/systemusers(2b3f3524-7856-e911-a82d-000d3a1a2282)', "
                                                            "'description': 'Call client to schedule follow up meeting', "
                                                            "'scheduledend': '2024-08-09T12:00:00Z', "
                                                            "'subject': 'Schedule Meeting', "
                                                            "'regardingobjectid_opportunity_task@odata.bind': '/opportunities(90cb1721-62ca-ee11-9079-0022481fb1b9)'} **\n"
                    "Assistant: 'I have created a task for the Red Roof Inn Account to call and schedule a meeting for 8.09.2024 at 12:00pm. You can view it at https://centricconsulting.crm.dynamics.com/main.aspx?pagetype=entitylist&etn=activitypointer&viewid=6cf285aa-eb20-4277-925a-3e9735411ff0&viewType=1039'\n"
                    "</TASK CREATION EXAMPLES>"
                    "<LEAD LOOKUP EXAMPLES>"
                    "User: Find me all leads created in the past 30 days for Columbus\n"
                    "** assistant uses tool dynamics-get_entities with**\n"
                    "'entity_type': 'businessunits', 'query_params': \"$$filter=contains(name, 'Columbus')\" **\n"
                    "** assistant uses tool dynamics-get_entities with**\n"
                    "'entity_type': 'leads', 'query_params': \"$$select=*&$$filter=createdon ge 2024-07-21 and _owningbusinessunit_value eq 5fa4a2f0-a754-e911-a82c-000d3a1a25b8&$$top=1&$$orderby=createdon desc\" **\n"
                    "Assistant: 'Here are the leads created since 2024-07-21.' "
                    "1. 'John Smith' - 'TBD' - 01/07/2024 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. 'Jack Taverns' - 'Fixing Problem' -  04/07/2024 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85\n"
                    "\n"
                    "User: Find me all leads created in the past month for Columbus\n"
                    "** assistant uses tool dynamics-get_entities with**\n"
                    "'entity_type': 'businessunits', 'query_params': \"$$filter=contains(name, 'Columbus')\" **\n"
                    "** assistant uses tool dynamics-get_entities with**\n"
                    "'entity_type': 'leads', 'query_params': \"$$select=*&$$filter=_owningbusinessunit_value eq 5fa4a2f0-a754-e911-a82c-000d3a1a25b8 and createdon ge 2024-06-30&$$top=1&$$orderby=createdon desc\" **\n"
                    "Assistant: 'Here are the leads created since 2024-07-21.' "
                    "1. 'John Smith' - 'TBD' - 01/07/2024 - 3462bf90-b6e7-ee11-904c-000d3a4f8a84 "
                    "2. 'Jack Taverns' - 'Fixing Problem' -  04/07/2024 - 3462bf90-b6e7-ee11-904c-000d3a4f8a85 "
                    "</LEAD LOOKUP EXAMPLES>"
                    "</EXAMPLES>")
        # Come back to this https://claude.ai/chat/6c747129-c21b-402b-a09c-c97b55c89fb5
        super().__init__(template=template, required=True, name="Dynamics CRM Search", render_section_header=True, **data)
