#from agent_c_tools.tools.web_search.duck_duck_go import DuckDuckGoTools
from agent_c_tools.tools.web_search.google_serp import GoogleSerpTools
from agent_c_tools.tools.web_search.google_trends import GoogleTrendsTools
from agent_c_tools.tools.web_search.hacker_news import HackerNewsTools
from agent_c_tools.tools.web_search.news_api import NewsApiTools
from agent_c_tools.tools.web_search.seeking_alpha import SeekingAlphaTools
from agent_c_tools.tools.web_search.tavily_research import TavilyResearchTools
from agent_c_tools.tools.web_search.wikipedia.tool import WikipediaTools
